In [1]:
import numpy as np
import tensorflow as tf

In [2]:
np.random.seed(101)
tf.set_random_seed(101)

In [3]:
rand_a = np.random.uniform(0, 100, (5,5))

In [4]:
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [7]:
rand_b = np.random.uniform(0, 100, (5,5))

In [8]:
rand_b

array([[99.43179012, 52.06653967, 57.87895355, 73.48190583, 54.19617722],
       [91.31535577, 80.7920151 , 40.29978307, 35.72243428, 95.28767147],
       [34.36315779, 86.50998163, 83.02777122, 53.81614492, 92.24693726],
       [ 9.71464798, 10.28474932, 70.15072957, 89.04798691, 15.95603009],
       [27.55725449, 67.24915297, 16.4303124 , 70.13711366, 48.76352222]])

In [9]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [11]:
add_op = a + b

In [12]:
mul_op = a * b

In [17]:
with tf.Session() as sess:
    add_result = sess.run(add_op, feed_dict={a:rand_a, b:rand_b})
    print(add_result)
    mul_R
    

In [18]:
add_result

array([[151.07166 , 109.1333  ,  60.726376,  90.63407 , 122.72388 ],
       [174.70505 , 111.48864 , 129.66109 , 107.87682 , 114.28157 ],
       [ 89.78592 , 121.723175, 101.21701 , 132.37631 , 188.79526 ],
       [ 32.950016,  18.640892, 130.50557 , 161.94727 ,  43.57991 ],
       [ 96.08789 , 119.035904,  21.278767,  83.92404 ,  67.460266]],
      dtype=float32)