In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
type(np.array(my_list))

numpy.ndarray

In [5]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])