In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.11.0


In [3]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
print(result)

b'Hello World'


In [11]:
a, b = tf.constant(10) ,tf.constant(20)

In [12]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [14]:
result

30

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4), 10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [21]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [22]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [23]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [24]:
sess = tf.InteractiveSession()

In [26]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.7906185  -0.3939899   0.60990083  0.18258062]
 [ 0.6772537   1.340755    0.02711209 -0.3994693 ]
 [-0.2721195  -0.48609424  0.44420135  0.36242467]
 [-1.3741391   0.36415577 -0.08800577 -1.2362481 ]]


[[0.74629545 0.8099015  0.11312091 0.25944316]
 [0.71929014 0.48638213 0.6844833  0.5332031 ]
 [0.7223333  0.89435446 0.8318479  0.1645788 ]
 [0.7295166  0.2709179  0.8981271  0.59583795]]




In [27]:
a = tf.constant([[1, 2], [3, 4]])

In [28]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [29]:
b = tf.constant([[10], [100]])

In [30]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
result = tf.matmul(a, b)

In [35]:
sess.run(result)

array([[210],
       [430]], dtype=int32)